// ============================================================
// Fichi — Airline IATA Code → Name Resolver
//
// Static map of the ~50 most common carriers. Returns the IATA
// code unchanged when not found.
// ============================================================

const AIRLINE_NAMES: Record<string, string> = {
  "2W": "World2Fly",
  AA: "American Airlines",
  AC: "Air Canada",
  AF: "Air France",
  AI: "Air India",
  AK: "AirAsia",
  AM: "Aeromexico",
  AS: "Alaska Airlines",
  AT: "Royal Air Maroc",
  AV: "Avianca",
  AY: "Finnair",
  AZ: "ITA Airways",
  BA: "British Airways",
  BR: "EVA Air",
  CA: "Air China",
  CI: "China Airlines",
  CX: "Cathay Pacific",
  CZ: "China Southern",
  DL: "Delta",
  EK: "Emirates",
  ET: "Ethiopian Airlines",
  EW: "Eurowings",
  EY: "Etihad",
  FI: "Icelandair",
  FR: "Ryanair",
  GA: "Garuda Indonesia",
  HA: "Hawaiian Airlines",
  HU: "Hainan Airlines",
  IB: "Iberia",
  JL: "Japan Airlines",
  KE: "Korean Air",
  KL: "KLM",
  KQ: "Kenya Airways",
  LA: "LATAM",
  LH: "Lufthansa",
  LO: "LOT Polish",
  LX: "Swiss",
  MH: "Malaysia Airlines",
  MS: "EgyptAir",
  MU: "China Eastern",
  NH: "ANA",
  NK: "Spirit",
  NZ: "Air New Zealand",
  OS: "Austrian",
  OZ: "Asiana",
  PC: "Pegasus",
  PR: "Philippine Airlines",
  QF: "Qantas",
  QR: "Qatar Airways",
  RJ: "Royal Jordanian",
  SA: "South African Airways",
  SK: "SAS",
  SN: "Brussels Airlines",
  SQ: "Singapore Airlines",
  SU: "Aeroflot",
  SV: "Saudia",
  TG: "Thai Airways",
  TK: "Turkish Airlines",
  TP: "TAP Portugal",
  U2: "easyJet",
  UA: "United",
  UX: "Air Europa",
  VN: "Vietnam Airlines",
  VS: "Virgin Atlantic",
  VY: "Vueling",
  W6: "Wizz Air",
  WN: "Southwest",
  WS: "WestJet",
};

/** Resolve an IATA carrier code to a human-readable airline name. */
export function getAirlineName(iataCode: string): string {
  return AIRLINE_NAMES[iataCode] ?? iataCode;
}
