// ============================================================
// Travel Pro — City → IATA Airport Code Lookup
//
// Used as a fallback when a city's iataCode is not populated
// by Stage A (Haiku route selector). Keys are lowercase city
// names; values are the main international airport IATA code.
//
// Coverage: ~200 major travel destinations worldwide.
// ============================================================

export const CITY_IATA_MAP: Record<string, string> = {
  // ── Europe ─────────────────────────────────────────────────
  london: "LHR",
  paris: "CDG",
  amsterdam: "AMS",
  berlin: "BER",
  rome: "FCO",
  barcelona: "BCN",
  madrid: "MAD",
  lisbon: "LIS",
  vienna: "VIE",
  prague: "PRG",
  budapest: "BUD",
  zurich: "ZRH",
  geneva: "GVA",
  brussels: "BRU",
  stockholm: "ARN",
  copenhagen: "CPH",
  oslo: "OSL",
  helsinki: "HEL",
  athens: "ATH",
  istanbul: "IST",
  dublin: "DUB",
  warsaw: "WAW",
  krakow: "KRK",
  dubrovnik: "DBV",
  split: "SPU",
  santorini: "JTR",
  mykonos: "JMK",
  nice: "NCE",
  venice: "VCE",
  florence: "FLR",
  milan: "MXP",
  edinburgh: "EDI",
  reykjavik: "KEF",
  porto: "OPO",
  seville: "SVQ",
  valencia: "VLC",
  lyon: "LYS",
  marseille: "MRS",
  frankfurt: "FRA",
  munich: "MUC",
  hamburg: "HAM",
  zurich: "ZRH",
  bern: "BRN",
  salzburg: "SZG",
  innsbruck: "INN",
  riga: "RIX",
  tallinn: "TLL",
  vilnius: "VNO",
  sofia: "SOF",
  bucharest: "OTP",
  belgrade: "BEG",
  zagreb: "ZAG",
  sarajevo: "SJJ",
  tirana: "TIA",
  skopje: "SKP",
  podgorica: "TGD",
  luxembourg: "LUX",
  valletta: "MLA",
  nicosia: "LCA",
  reykjavik: "KEF",
  // ── East Asia ──────────────────────────────────────────────
  tokyo: "NRT",
  osaka: "KIX",
  kyoto: "ITM",
  hiroshima: "HIJ",
  sapporo: "CTS",
  fukuoka: "FUK",
  nagoya: "NGO",
  naha: "OKA",
  seoul: "ICN",
  busan: "PUS",
  jeju: "CJU",
  beijing: "PEK",
  shanghai: "PVG",
  guangzhou: "CAN",
  shenzhen: "SZX",
  chengdu: "CTU",
  chongqing: "CKG",
  xi_an: "XIY",
  "xi'an": "XIY",
  xian: "XIY",
  guilin: "KWL",
  zhangjiajie: "DYG",
  hong_kong: "HKG",
  "hong kong": "HKG",
  hongkong: "HKG",
  macau: "MFM",
  taipei: "TPE",
  kaohsiung: "KHH",
  ulaanbaatar: "ULN",
  // ── Southeast Asia ─────────────────────────────────────────
  singapore: "SIN",
  bangkok: "BKK",
  "chiang mai": "CNX",
  chiangmai: "CNX",
  phuket: "HKT",
  "koh samui": "USM",
  kohsamui: "USM",
  krabi: "KBV",
  "hat yai": "HDY",
  hanoi: "HAN",
  "ho chi minh city": "SGN",
  "ho chi minh": "SGN",
  saigon: "SGN",
  "da nang": "DAD",
  danang: "DAD",
  "hoi an": "DAD",
  hoian: "DAD",
  hue: "HUI",
  "ha long bay": "HPH",
  "halong bay": "HPH",
  "ha long": "HPH",
  halong: "HPH",
  "nha trang": "CXR",
  nhatrang: "CXR",
  "phu quoc": "PQC",
  kuala_lumpur: "KUL",
  "kuala lumpur": "KUL",
  kualalumpur: "KUL",
  penang: "PEN",
  kota_kinabalu: "BKI",
  "kota kinabalu": "BKI",
  langkawi: "LGK",
  johor_bahru: "JHB",
  "johor bahru": "JHB",
  jakarta: "CGK",
  bali: "DPS",
  denpasar: "DPS",
  yogyakarta: "YIA",
  surabaya: "SUB",
  lombok: "LOP",
  "labuan bajo": "LBJ",
  manila: "MNL",
  cebu: "CEB",
  "el nido": "ENI",
  boracay: "MPH",
  phnom_penh: "PNH",
  "phnom penh": "PNH",
  siem_reap: "REP",
  "siem reap": "REP",
  vientiane: "VTE",
  luang_prabang: "LPQ",
  "luang prabang": "LPQ",
  rangoon: "RGN",
  yangon: "RGN",
  mandalay: "MDL",
  // ── South Asia ─────────────────────────────────────────────
  delhi: "DEL",
  "new delhi": "DEL",
  mumbai: "BOM",
  bangalore: "BLR",
  bengaluru: "BLR",
  chennai: "MAA",
  kolkata: "CCU",
  goa: "GOI",
  jaipur: "JAI",
  agra: "AGR",
  varanasi: "VNS",
  kochi: "COK",
  hyderabad: "HYD",
  ahmedabad: "AMD",
  amritsar: "ATQ",
  kathmandu: "KTM",
  colombo: "CMB",
  dhaka: "DAC",
  karachi: "KHI",
  lahore: "LHE",
  islamabad: "ISB",
  // ── Central Asia & Caucasus ────────────────────────────────
  tashkent: "TAS",
  samarkand: "SKD",
  almaty: "ALA",
  astana: "NQZ",
  tbilisi: "TBS",
  yerevan: "EVN",
  baku: "GYD",
  // ── Middle East ────────────────────────────────────────────
  dubai: "DXB",
  "abu dhabi": "AUH",
  abudhabi: "AUH",
  doha: "DOH",
  muscat: "MCT",
  riyadh: "RUH",
  jeddah: "JED",
  amman: "AMM",
  "tel aviv": "TLV",
  telaviv: "TLV",
  jerusalem: "TLV",
  beirut: "BEY",
  tehran: "IKA",
  baghdad: "BGW",
  kuwait: "KWI",
  "kuwait city": "KWI",
  // ── Africa ─────────────────────────────────────────────────
  cairo: "CAI",
  luxor: "LXR",
  "sharm el sheikh": "SSH",
  marrakech: "RAK",
  marrakesh: "RAK",
  casablanca: "CMN",
  fez: "FEZ",
  tunis: "TUN",
  algiers: "ALG",
  tripoli: "MJI",
  nairobi: "NBO",
  mombasa: "MBA",
  zanzibar: "ZNZ",
  "dar es salaam": "DAR",
  arusha: "ARK",
  kampala: "EBB",
  kigali: "KGL",
  addis_ababa: "ADD",
  "addis ababa": "ADD",
  accra: "ACC",
  lagos: "LOS",
  abuja: "ABV",
  dakar: "DSS",
  abidjan: "ABJ",
  "cape town": "CPT",
  capetown: "CPT",
  johannesburg: "JNB",
  durban: "DUR",
  victoria_falls: "VFA",
  "victoria falls": "VFA",
  windhoek: "WDH",
  gaborone: "GBE",
  lusaka: "LUN",
  harare: "HRE",
  antananarivo: "TNR",
  mauritius: "MRU",
  seychelles: "SEZ",
  mahe: "SEZ",
  // ── North America ──────────────────────────────────────────
  "new york": "JFK",
  newyork: "JFK",
  manhattan: "JFK",
  "los angeles": "LAX",
  losangeles: "LAX",
  "san francisco": "SFO",
  sanfrancisco: "SFO",
  chicago: "ORD",
  miami: "MIA",
  "las vegas": "LAS",
  lasvegas: "LAS",
  "new orleans": "MSY",
  neworleans: "MSY",
  washington: "DCA",
  "washington dc": "DCA",
  boston: "BOS",
  seattle: "SEA",
  denver: "DEN",
  atlanta: "ATL",
  dallas: "DFW",
  houston: "IAH",
  phoenix: "PHX",
  portland: "PDX",
  minneapolis: "MSP",
  nashville: "BNA",
  charleston: "CHS",
  savannah: "SAV",
  orlando: "MCO",
  "san diego": "SAN",
  sandiego: "SAN",
  "san jose": "SJC",
  sanjose: "SJC",
  honolulu: "HNL",
  maui: "OGG",
  anchorage: "ANC",
  vancouver: "YVR",
  toronto: "YYZ",
  montreal: "YUL",
  calgary: "YYC",
  ottawa: "YOW",
  quebec: "YQB",
  // ── Mexico & Central America ───────────────────────────────
  "mexico city": "MEX",
  mexicocity: "MEX",
  cancun: "CUN",
  tulum: "CUN",
  playa_del_carmen: "CUN",
  "playa del carmen": "CUN",
  guadalajara: "GDL",
  monterrey: "MTY",
  oaxaca: "OAX",
  san_cristobal: "SZT",
  havana: "HAV",
  "san jose": "SJO",
  "san josé": "SJO",
  "panama city": "PTY",
  // ── South America ──────────────────────────────────────────
  bogota: "BOG",
  cartagena: "CTG",
  medellin: "MDE",
  lima: "LIM",
  cusco: "CUZ",
  "machu picchu": "CUZ",
  machupicchu: "CUZ",
  quito: "UIO",
  galapagos: "GPS",
  "buenos aires": "EZE",
  buenosaires: "EZE",
  santiago: "SCL",
  "rio de janeiro": "GIG",
  riodejaneiro: "GIG",
  "sao paulo": "GRU",
  saopaulo: "GRU",
  "são paulo": "GRU",
  montevideo: "MVD",
  asuncion: "ASU",
  lapaz: "LPB",
  "la paz": "LPB",
  sucre: "SRE",
  "santa cruz": "VVI",
  caracas: "CCS",
  // ── Oceania ────────────────────────────────────────────────
  sydney: "SYD",
  melbourne: "MEL",
  brisbane: "BNE",
  perth: "PER",
  adelaide: "ADL",
  cairns: "CNS",
  darwin: "DRW",
  "gold coast": "OOL",
  auckland: "AKL",
  queenstown: "ZQN",
  christchurch: "CHC",
  wellington: "WLG",
  fiji: "NAN",
  suva: "SUV",
  nadi: "NAN",
  "port moresby": "POM",
  noumea: "NOU",
  "papeete": "PPT",
  tahiti: "PPT",
};

/**
 * Look up the IATA airport code for a city name.
 * Case-insensitive. Returns undefined if not found.
 */
export function lookupIata(city: string): string | undefined {
  return CITY_IATA_MAP[city.toLowerCase().trim()];
}
